### ISSUE TITLE
ESP-WROOM-32 - Alert sequence from meter

### ISSUE THREAD

**Issue by FootlockerX** [DabblerDK/MEP-SW-ESP32#1]
Hi Dabbler

First of all thanks for your great work and I have already ordered the NES MEP interface kit.
Im in contact with my power provider in Denmark (Cerius) and got an encryption key for the MEP port.

Before the MEP interface kit arrives, I have tried to get data out of my Cerius Echelon/NES smartmeter and into a ESP-Wroom-32 with dabbler software on it.

The error Im getting from the "home screen" will be attached to this message 
![error](https://user-images.githubusercontent.com/109248802/193505851-33f3051d-6968-4565-b741-c1f6256e433c.png)

I realise that in order to troubbleshoot errors, you will need info on my setup.

**Encryptionkey:**
the encryption key I received from Cerius is 20 chars in lenght, Cerius suggested to remove the last 4 chars of the key, which did not change the outcome.

**MEP port pinout:**
Cerius MEP pinout found here https://cerius.dk/wp-content/uploads/tilslutningsmulighed-for-mep-udstyr-i-elmaaler-type-echelon-gen-31-og-32.pdf

I have mirrored the pins on the Cerius documentation for the MEP port, since the documentation is for the male connector and not the female one.
the picture below was confirmed by a Cerius technician
![MEP pinout](https://user-images.githubusercontent.com/109248802/193504201-18b891e9-11be-493e-924c-b2f505478bf6.png)

Pin 1 is GND
Pin 2 is TxD
Pin 5 is RxD

**ESP-WROOM-32 pinout:**
My ESP is powered by an external samsung mobile charger (usb to microusb).
![ESP32-Pinout-1](https://user-images.githubusercontent.com/109248802/193504831-f5f2359a-99db-4e4d-87df-3d4305ac7061.jpg)

 I have connected,
Pin 17 on the ESP to pin 1 on the MEP port
Pin 21 on the ESP to pin 2 on the MEP port
Pin 22 on the ESP to pin 5 on the MEP port

Any suggestions on how to solve my issue?

**Comment by Kilsgaard** [comment]
Hi

You can find our description of the pin layout in the following blogpost on dabbler.dk

- https://www.dabbler.dk/index.php/2021/10/27/echelon-nes-smart-meters-dabbling-the-hardware-v1-00/

You cannot connect the ESP direct to the MEP port, the MEP port is running RS232 so you need something to generate RS232.
ex. the MAX3232 that we use to communicate with MEP.

Also remember that the enable port (pin 2) have to be kept high when communicating.
We do that with one of the ports on the MAX3232.

**Comment by glynge** [comment]
Hi

While it is true you only need the first 16 characters of the key, our software don't care (it removes the unneeded characters if present). So it won't make any difference with our software.

As Graves states you need to convert the RS232 (which is typically +/- 9v or +/- 12v signal levels) to 3.3v TTL levels that the ESP32 uses. The easiest way of doing that is with a MAX3232 and a handful of capacitors (i uses those for the internal boost converter to boost it's 3.3v supply to +/- 9v I think?)... Beware - there is a lot of fake MAX3232s in DIP16 out there... 
The MAX3232 can get it's power from the ESP32. It uses only a few mA.
You might have fried your ESP32 with the RS232 signals, but probably not if you didn't set the ENABLE pin to high (5 to 12v).

You must set the ENABLE pin on the MEP connector high (5 to 12v) just like Graves states. Without that you will not get any output from the meter as the power provided on ENABLE is used to drive the TxD pin from the meter. 
No power on ENABLE = no power on TxD :-).

Please see our schematics for details on how to hook it up...
If you don't have KiCad let us know and we will provide a PDF.

Note/hint: For testing you can just attach a 9v battery between ENABLE and GND (we did that for testing previously).

Btw: 00 00 is the alarm sequence the meter can send to the module. That is the only communication the Meter can initiate - all other data packages are responses to requests you send to it.
Alarm means that the software should then query the meter to ask what is wrong. It might be as simple as it needs data to provide to the HUB (i.e. the MEP port can hook up a water meter and then the readouts from it can be collected and sent to the power company along with the power meter readings). I can also be a lot of other things.
In your case it is most likely garbage/electric noise if you didn't hook up the ENABLE pin.

Please let us know if you have further questions.

**Comment by glynge** [comment]
Closing the issue as this is not our hardware/nothing we can fix in software
