### ISSUE TITLE
Unable to log on wifi AP on first startup. Wrong code

### ISSUE THREAD

**Issue by Ferforfaen** [DabblerDK/MEP-SW-ESP32#11]
Hi. 

Just bought the board from ustepper, but i am not able to log on to the wifi-AP (esp32-mep) I have tried 12345678. Wrong code. I am not able to use 123456. Probably as its WPA2, and 8 characters long code. 

Any ideas?

**Comment by glynge** [comment]
Hi, the correct code for the AP in the never software versions supporting the uStepper hardware  is 12345678.
If it does not work, please try to use another device to do the initial setup.
Please let me know if you get it working, if not I can try to build a software for you with another password.

**Comment by Ferforfaen** [comment]
That would be very nice Glynge. I have tried on a macbook pro, a old iMac 24", iPhone 14 and an older HP windows 10 laptop. All of them report wrong password

**Comment by glynge** [comment]
Strange. Please e-mail me on gert@dabbler.dk and I'll reply with a private build software for your uStepper module.
I hope you have a way of flashing it?
If not, the best solution would probably be for you to clone the software yourself. Install the Arduino IDE, change the password yourself - and then flash the module from there...

**Comment by Ferforfaen** [comment]
Thank you so much, send you an email :)

**Comment by Ferforfaen** [comment]
Reflashed the module with the firmware from github, and suddenly it worked. No idea why
