### ISSUE TITLE
Dataflow from meter 0x0B Authentication failure

### ISSUE THREAD

**Issue by Ferforfaen** [DabblerDK/MEP-SW-ESP32#12]
Hi

I have had problems with my dabbler unit crashing. 

Symptoms:
All Home Assistant entities becomes unavailable
If i connect to the web ui, all values are 0. 

Normally a reset by the microswitch solves it. Today it was a bit more stubborn, and I got the log. 
As seen here, it seems a bit intermittent. Both the total reading and the meter readings fail, and then the work again. 

It is installed in a 3 month old meter, with the breakout kit. 
Any ideas? 
<img width="1656" alt="Skærmbillede 2023-09-25 kl  20 59 30" src="https://github.com/DabblerDK/MEP-SW-ESP32/assets/70026175/9131eb4b-392a-4d22-82a6-730085d133fa">

**Comment by Kannut** [comment]
I seem to be having the same or similar problem. Just received a brand new preinstalled from ustepper and it worked great the first day. A few times the "MEP problem" in Home Assistant reported a problem bit after a few minutes all was fine. Happened 5 times. But today I have the problem as OK but receive 0 for all values. Tried unplugging and plugged the module in again and now still just 0s

![Screenshot_20231008_082753_Chrome](https://github.com/DabblerDK/MEP-SW-ESP32/assets/75672263/6fc80f65-3673-4349-94ba-ad5e59f359ba)

**Comment by glynge** [comment]
Hi Ferforfaen and Kannut

Sorry for the late answer.

Please reach out to uStepper on contact@ustepper.com.

Others have seen this problem before and it seems it is a power issue on the board causing the ESP32 to be unstable.
Should be possible to test by supplying external power and they have a fix as far as we know. But please reach out to them to get the details.

Best regards
gert@dabbler.dk
