### ISSUE TITLE
Add mqtt Home Assistant example to readme

### ISSUE THREAD

**Issue by DIYtechie** [DabblerDK/MEP-SW-ESP32#13]
Thanks for making this cool open source project.

Just wanted to say that I spent some time setting the dabbler module up via mqtt in Home Assistant. Would be nice with an example configuration. I finally set up the main entities and this works (feel free to add as example in README):

`mqtt:
  sensor:
  - name: "Echelon power draw total (live)"
    availability_topic: "dabbler/lwt"
    payload_available: "Online"
    payload_not_available: "Offline"
    state_topic: "dabbler/meterConsumptionFwd/mydatajson"
    value_template: '{{ value_json.Fwd_W }}'
    unit_of_measurement: "W"

  - name: "Echelon L1 power draw"
    availability_topic: "dabbler/lwt"
    payload_available: "Online"
    payload_not_available: "Offline"
    state_topic: "dabbler/meterConsumptionFwd/mydatajson"
    value_template: '{{ value_json.L1_Fwd_W }}'
    unit_of_measurement: "W"
    
  - name: "Echelon L2 power draw"
    availability_topic: "dabbler/lwt"
    payload_available: "Online"
    payload_not_available: "Offline"
    state_topic: "dabbler/meterConsumptionFwd/mydatajson"
    value_template: '{{ value_json.L2_Fwd_W }}'
    unit_of_measurement: "W"

  - name: "Echelon L3 power draw"
    availability_topic: "dabbler/lwt"
    payload_available: "Online"
    payload_not_available: "Offline"
    state_topic: "dabbler/meterConsumptionFwd/mydatajson"
    value_template: '{{ value_json.L3_Fwd_W }}'
    unit_of_measurement: "W"
    
  - name: "Echelon total energy consumption"
    availability_topic: "dabbler/lwt"
    payload_available: "Online"
    payload_not_available: "Offline"
    state_topic: "dabbler/meterConsumptionTotal/mydatajson"
    value_template: '{{ value_json.Fwd_Act_Wh }}'
    unit_of_measurement: "Wh"`

**Comment by glynge** [comment]
Thanks for your contribution, I'll add it to the README shortly.
