### ISSUE TITLE
Sum for forward and reverse watt

### ISSUE THREAD

**Issue by AMajland** [DabblerDK/MEP-SW-ESP32#4]
I have a little bit of sun today and have been looking at the dashboard.

I've noticed that the L1L2L3 Forward Watt and Reverse Watt are exclusive as if i had a meter working after the summation principle.

N1 has confirmed that the total Forward and Reverse kwh can be increase at the same time when i have excess producion on one or two phases and draw more fromt the last. 

![image](https://user-images.githubusercontent.com/97510471/199001068-7a08e843-a18e-4ebb-8525-53bfa90e3efa.png)

The picture shows that i'm drawing from L1 while delivering excesss og L2 and L3.

So i would have ecpeted the  L1L2L3 Forward Watt to show the same as L1

But there are probably some other registers to read for that ....

I dobn't understand the Forward current either. When the forward W is 0 the current should be the same :-)

Time to look at the code ...

**Comment by AMajland** [comment]
I generelly have more load on L1 (home office) and L3 (dishhwasher) but seen them all shift 

![image](https://user-images.githubusercontent.com/97510471/199003025-fb1c1d4a-6ee5-4a2d-9b26-e24c740a625c.png)

**Comment by glynge** [comment]
Hi AMajland,

I agree.
This seems totally wrong and after revisiting the documentation I'm pretty sure our decoding of the mili Amp. is flawed.
If you go to page 215 in the MEP documentation (you'll find it here: https://github.com/OSGP-Alliance-MEP-and-Optical/Documentation) you will see the definition of the 0x001C table.

If I recall this correctly, we are grabbing the mili Amp. values from field 4, 5 and 6 - but they don't state if it is Forward or Reverse.
And the format is NI_FMAT1, which is 4-byte signed integer format.
So these 3 fields are both Forward and Reverse and are supposed to be able to go negative.
That probably explains your REALLY high figures here. I guess you are not consuming 4A on each phase (which would be around 1KWatt on each) while actually sending power to the grid according to the Reverse Watt figures.
The mili Amp. figures should probably be a negative number instead.

Regarding the Forward and Reverse L1L2L3 Watt it might be we are also reading the wrong fields.
Would it be possible for you to provide me with some of the "0x30 Full Table Read 0x001C BT28 Present Register Data" request, responses and decodede data from the table on the modules "Home" page when you are sending power to the grid?

Note: I'm involved in a large ERP upgrade at work, for the next few weeks - so I might be hard to get in touch with.
I'm sorry for that, but naturally I need to prioritize my work :-).

**Comment by AMajland** [comment]
Sure, i'll wait for the sun to get up (hopefully today) - the forecost is not that promissing for producing more than i consume.

But it was interesting to see that the meter supports reading the summation values (showing either forward or reverse) - but it is just not those that N1 (the meter companies) retrieves for billing.

Btw my 83331-3I has Firmware: 58.134

I still need to get the environment set up to compile the code - and not least read and understand it

**Comment by AMajland** [comment]
Does'nt look like we will get any sun today - So just testing a copy paste of the table

<html>
<body>


Index | Millis | Request | Tries | Response | Decoded Request and Response | Next Action
-- | -- | -- | -- | -- | -- | --
0 | 175071684 | 00 11 30 00 1c 02 00 c9 74 d0 58 cc 54 8d 90 95 ec 00 d4 | 1 | 00 e7 00 00 dc 8f 01 00 00 00 00 00 00 00 00 00 00 bf 03 00 00 3d 0b 00 00 15 06 00 00 71 08 00 00 63 71 03 00 5f 7a 03 00 c3 79 03 00 c3 01 00 00 82 c3 00 00 d3 05 00 00 f1 00 00 00 2d 00 00 00 96 fd ff ff c9 fe ff ff 6e fc ff ff 8f 01 00 00 00 00 00 00 00 00 00 00 bf 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 bf 03 00 00 24 01 00 00 55 00 00 00 16 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 24 01 00 00 55 00 00 00 16 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 3d 0b 00 00 15 06 00 00 71 08 00 00 9b 75 03 00 db 7b 03 00 eb 76 03 00 43 7e 03 00 c3 85 03 00 97 7e 03 00 8f 01 00 00 00 00 00 00 24 01 00 00 55 00 00 00 16 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 d6 95 ad 99 31 35 ce af | 0x30 Full Table Read 0x001C BT28 Present Register DataMeter response: 0x00 Successful responseFwd Active W L1L2L3: 399Rev Active W L1L2L3: 0Import Reactive VAr L1L2L3: 0Export Reactive VAr L1L2L3: 959RMS Current (mA) L1: 2877RMS Current (mA) L2: 1557RMS Current (mA) L3: 2161RMS Voltage (mV) L1: 225635RMS Voltage (mV) L2: 227935RMS Voltage (mV) L3: 227779Frequency (mHz): 50050VA L1L2L3: 1491Power Factor L1 (1/1000): 451Power Factor L2 (1/1000): 241Power Factor L3 (1/1000): 45Fwd Active W L1: 292Fwd Active W L2: 85Fwd Active W L3: 22Rev Active W L1: 0Rev Active W L2: 0Rev Active W L3: 0RMS Voltage (mV) L1 - Continuous: 226715RMS Voltage (mV) L2 - Continuous: 228315RMS Voltage (mV) L3 - Continuous: 227051RMS Voltage (mV) L1 - Average: 228931RMS Voltage (mV) L2 - Average: 230851RMS Voltage (mV) L3 - Average: 229015Average Fwd Active W L1L2L3: 399Average Rev Active W L1L2L3: 0Average Fwd Active W L1: 292Average Fwd Active W L2: 85Average Fwd Active W L3: 22Average Rev Active W L1: 0Average Rev Active W L2: 0Average Rev Active W L3: 0


</body>
</html>

Og så kom solen alligevel

<html>
<body>


Index | Millis | Request | Tries | Response | Decoded Request and Response | Next Action
-- | -- | -- | -- | -- | -- | --
0 | 176633863 | 00 11 30 00 1c 02 00 c9 74 d5 bc 8b 5f 08 11 67 ea 57 1c | 1 | 00 e7 00 00 dc 00 00 00 00 23 0b 00 00 00 00 00 00 15 03 00 00 26 10 00 00 0c 14 00 00 57 12 00 00 24 7b 03 00 1d 89 03 00 c7 78 03 00 07 fd ff ff 50 c3 00 00 7d 0c 00 00 38 fc ff ff 5a fc ff ff 81 fe ff ff 64 ff ff ff 1e ff ff ff 00 00 00 00 23 0b 00 00 00 00 00 00 15 03 00 00 00 00 00 00 00 00 00 00 15 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 c4 02 00 00 7a 04 00 00 e5 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 c4 02 00 00 7a 04 00 00 e5 03 00 00 31 10 00 00 ea 13 00 00 61 12 00 00 cf 7a 03 00 a9 85 03 00 4b 7b 03 00 4c 75 03 00 b4 7c 03 00 4a 76 03 00 00 00 00 00 23 0b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 c4 02 00 00 7a 04 00 00 e5 03 00 00 c4 87 65 47 60 0b bb c9 | 0x30 Full Table Read 0x001C BT28 Present Register DataMeter response: 0x00 Successful responseFwd Active W L1L2L3: 0Rev Active W L1L2L3: 2851Import Reactive VAr L1L2L3: 0Export Reactive VAr L1L2L3: 789RMS Current (mA) L1: 4134RMS Current (mA) L2: 5132RMS Current (mA) L3: 4695RMS Voltage (mV) L1: 228132RMS Voltage (mV) L2: 231709RMS Voltage (mV) L3: 227527Frequency (mHz): 50000VA L1L2L3: 3197Power Factor L1 (1/1000): -761Power Factor L2 (1/1000): -968Power Factor L3 (1/1000): -934Fwd Active W L1: 0Fwd Active W L2: 0Fwd Active W L3: 0Rev Active W L1: 708Rev Active W L2: 1146Rev Active W L3: 997RMS Voltage (mV) L1 - Continuous: 228047RMS Voltage (mV) L2 - Continuous: 230825RMS Voltage (mV) L3 - Continuous: 228171RMS Voltage (mV) L1 - Average: 226636RMS Voltage (mV) L2 - Average: 228532RMS Voltage (mV) L3 - Average: 226890Average Fwd Active W L1L2L3: 0Average Rev Active W L1L2L3: 2851Average Fwd Active W L1: 0Average Fwd Active W L2: 0Average Fwd Active W L3: 0Average Rev Active W L1: 708Average Rev Active W L2: 1146Average Rev Active W L3: 997


</body>
</html>

**Comment by AMajland** [comment]
Maybe an idea with a download link to export comma seperated

![image](https://user-images.githubusercontent.com/97510471/199235772-6d439292-3096-4704-a2ef-d82aea42c67a.png)

**Comment by AMajland** [comment]
Forward and reverse power at the same time 

<html>
<body>


Index | Millis | Request | Tries | Response | Decoded Request and Response | Next Action
-- | -- | -- | -- | -- | -- | --
0 | 176997159 | 00 11 30 00 1c 02 00 c9 74 d6 fc b7 5f fa ff fe d2 22 e7 | 1 | 00 e7 00 00 dc 37 01 00 00 00 00 00 00 00 00 00 00 29 04 00 00 8f 0c 00 00 77 08 00 00 18 0b 00 00 3f 7b 03 00 8d 81 03 00 33 7a 03 00 06 02 00 00 82 c3 00 00 4b 07 00 00 0d ff ff ff 45 00 00 00 e8 fd ff ff 9a fd ff ff bf fd ff ff 37 01 00 00 00 00 00 00 00 00 00 00 29 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 29 04 00 00 83 01 00 00 00 00 00 00 2c 00 00 00 00 00 00 00 77 00 00 00 00 00 00 00 83 01 00 00 00 00 00 00 2c 00 00 00 00 00 00 00 77 00 00 00 00 00 00 00 c8 0c 00 00 56 08 00 00 ee 0a 00 00 27 7a 03 00 ef 81 03 00 37 79 03 00 4c 75 03 00 b4 7c 03 00 4a 76 03 00 37 01 00 00 00 00 00 00 83 01 00 00 00 00 00 00 2c 00 00 00 00 00 00 00 77 00 00 00 00 00 00 00 bc 7b 66 1e 90 b7 ba 54 | 0x30 Full Table Read 0x001C BT28 Present Register DataMeter response: 0x00 Successful responseFwd Active W L1L2L3: 311Rev Active W L1L2L3: 0Import Reactive VAr L1L2L3: 0Export Reactive VAr L1L2L3: 1065RMS Current (mA) L1: 3215RMS Current (mA) L2: 2167RMS Current (mA) L3: 2840RMS Voltage (mV) L1: 228159RMS Voltage (mV) L2: 229773RMS Voltage (mV) L3: 227891Frequency (mHz): 50050VA L1L2L3: 1867Power Factor L1 (1/1000): 518Power Factor L2 (1/1000): -243Power Factor L3 (1/1000): 69Fwd Active W L1: 387Fwd Active W L2: 0Fwd Active W L3: 44Rev Active W L1: 0Rev Active W L2: 119Rev Active W L3: 0RMS Voltage (mV) L1 - Continuous: 227879RMS Voltage (mV) L2 - Continuous: 229871RMS Voltage (mV) L3 - Continuous: 227639RMS Voltage (mV) L1 - Average: 226636RMS Voltage (mV) L2 - Average: 228532RMS Voltage (mV) L3 - Average: 226890Average Fwd Active W L1L2L3: 311Average Rev Active W L1L2L3: 0Average Fwd Active W L1: 387Average Fwd Active W L2: 0Average Fwd Active W L3: 44Average Rev Active W L1: 0Average Rev Active W L2: 119Average Rev Active W L3: 0


</body>
</html>

![image](https://user-images.githubusercontent.com/97510471/199236413-542362c1-0a4b-40cf-9959-19f93a3dd4fc.png)

**Comment by glynge** [comment]
Thanks. I'll for sure look into this as soon as time permits...

**Comment by edenhome** [comment]
I would say the amps show correct,, on an AC circuit, the amps will be the same whether its import or export, but the power factor will go negative when exporting

**Comment by AMajland** [comment]
In the first picture the current for L1 is shown as 3 A but the power is 414W / 0. 

On the second picture the multiply of current and voltage issue <> Reverse Watt
928	 <> 742
1082 <> 1007
951  <> 918

It seems to be a rather big difference but may be due the phase betweem them 

But it may also just be update issue of the graphics when the power fluctuates.

**Comment by edenhome** [comment]
without comparing with the powerfactor, nothing is to big or small,,, you could easy have 6amp and 20W, if you had a cheap induction cooker or something like that connected

**Comment by AMajland** [comment]
Point taken. I looked at the numbers too superficially.

But I still need the numbers for simultaneous power flow back and forth because that what the meter is using for the energy registers. That is if i'm selling on L2 and L3 while buying on L1 both the counters will be increasing.

(Yes i know - gotta look into it myself, but now gotten to it yet :-) )

**Comment by glynge** [comment]
Sorry for being absent. Big ERP upgrade in progress at work, so I don't have any spare time at the moment. I'll look into this issue later on...

**Comment by glynge** [comment]
After looking into this and reading all the comments, my conclusion is that we cannot fix this in the software.
Our module and software is only supposed to be a gateway between WIFI and the MEP-interface, we don't want to add to the dataset in any way. This can be done in systems consuming the MQTT or the webservice.
